
# Happy Coding! go fuck yourself

service: web-scraper # NOTE: update this with your service name

provider:
  name: aws
  runtime: python3.6
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - polly:*
      Resource: "*"
    - Effect: "Allow"
      Action:
        - s3:*
      Resource: "*"

functions:
  web_scraper:
    handler: handler.web_scraper


plugins:
  - serverless-python-requirements


custom:
  pythonRequirements:
    dockerizePip: true

