service: web-scraper # NOTE: update this with your service name

provider:
  name: aws
  runtime: python3.6
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - polly:*
      Resource: "*"

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
    fileName: requirements.txt

  functions:
  web_scraper:
    handler: handler.web_scraper

